-- CREATE TABLE IF NOT EXISTS comments (
--     comments_id SERIAL PRIMARY KEY,
--     project_id VARCHAR(100) REFERENCES projects(project_id) ON DELETE CASCADE,
--     user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
--     comments TEXT
-- );